# Generated by Django 6.0.8 on 2026-09-24 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='🛍️', max_length=12, verbose_name='emoji')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('platform', models.CharField(choices=[('Mercado Livre', 'Mercado Livre'), ('Shopee', 'Shopee'), ('Amazon', 'Amazon'), ('Outra', 'Outra')], max_length=30, verbose_name='plataforma')),
                ('affiliate_url', models.URLField(max_length=1000, verbose_name='link de afiliado')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='URL da imagem')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='imagem enviada')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço atual')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço antigo')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('active', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ofertas.product')),
            ],
            options={
                'verbose_name': 'clique registrado',
                'verbose_name_plural': 'cliques registrados',
                'ordering': ['-created_at'],
            },
        ),
    ]
